### ISSUE TITLE
Unknown props `xs`, `md` on <div> tag

### ISSUE THREAD

**Issue by zp1112** [roylee0704/react-flexbox-grid#45]
it looks like node_modules missing something when I remove node_modules and renpm package.json.

**Comment by silvenon** [comment]
Which steps are required to reproduce this error?

**Comment by carlgunderson** [comment]
This seems like a duplicate of #38 as well

**Comment by lucafaggianelli** [comment]
On React there is an issue that describes why this warning happens:
https://github.com/facebook/react/issues/7301

I also experienced a warning for the 'fluid' prop in <Grid>:

`Unknown prop `fluid` on <div> tag`

**Comment by smeijer** [comment]
So is there a temporary fix available?

**Comment by NeXTs** [comment]
@smeijer only [this](https://github.com/roylee0704/react-flexbox-grid/pull/38#issuecomment-234404729), as for now

**Comment by smeijer** [comment]
@NeXTs awesome! Thanks.

Changed `package.json` to include `"react-flexbox-grid": "vipoo/react-flexbox-grid#deans-dev"`, and it worked perfectly for now.

Hope this issue will be fixed soon so I can revert back to the original version.

**Comment by roylee0704** [comment]
@smeijer, new version 0.10.0 is up. Sorry for the wait.

**Comment by mauriciominella** [comment]
Has it been fixed on version 0.10.0? I'm using 0.10.2 and still getting the same error.

**Comment by efeminella** [comment]
Has this been resolved? I've updated to 1.1.5 and the issue is still present:

warning.js:33 Warning: Unknown prop `xs` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Row)
    in Row (created by CoreLayout)
    in div (created by Grid)
    in Grid (created by CoreLayout)
    in CoreLayout (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by AppContainer)
    in div (created by AppContainer)
    in Provider (created by AppContainer)
    in MuiThemeProvider (created by AppContainer)
    in AppContainer
    in Translate(AppContainer)
    in I18nextProvider
